### PR TITLE
fix: button favorite and 3 dots menu in activity detail have no accessible name - EXO-62416

### PR DESCRIPTION
**Pull request by akhanfir**
Before this change, after creating an activity in a space when you open DevTools of your browser and in the flagship tab, run the accessibility check, the favorite button and the 3 dots menu button have no accessible name. To resolve this problem, in the News_eu.properties file, added the labels following find it easily when searching, Remove from favorites and Open activity menu to the Archive article, Unarchive article and menu 3 buttons points of the activity. After this change, these faulty elements are no longer displayed in the flagship tab, launch accessibility.

### CODE REVIEW

**Review by rdenarie — CHANGES_REQUESTED** [review]
Why this modification is only for news module ? 

The problem is for all activities, please modify in social module, so that all activities are ifxed in once

**Comment by akhanfir** [comment]
https://github.com/Meeds-io/social/pull/3254

**Review by ahamdi — DISMISSED** [review]

**Review by Jihed525 — APPROVED** [review]

**Review by Jihed525 — DISMISSED** [review]

**Comment by ahamdi** [comment]
@rdenarie Could you recheck this PR ?

**Comment by rdenarie** [comment]
We need a rebase and fix conflict.

My precedent remark was : 

> Why this modification is only for news module ?
> The problem is for all activities, please modify in social module, so that all activities are ifxed in once

So I'm not sure it is necessary to modify something in news module

**Comment by akhanfir** [comment]
ok, so do I close this PR? @rdenarie

**Comment by Jihed525** [comment]
> ok, so do I close this PR? @rdenarie

@rdenarie do we close this PR ?

**Comment by rdenarie** [comment]
@akhanfir you dit not answer my question : 
`Why this modification is only for news module ?
The problem is for all activities, please modify in social module, so that all activities are ifxed in once`

So, if you make the modification for all activities in social, this one can be closed.

**Comment by Jihed525** [comment]
> is one can be

Just checked it with @akhanfir and this pr covers labels for news details, the news module has it's own class https://github.com/exoplatform/news/pull/1001/files#diff-6646b546eb52e2926afcc18c611226769e000126c5bb850113426861f44b8c80L14

wdyt @rdenarie .?

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
