### PR TITLE
TASK-52070: Add role presentation for decorative images in news detail page

### PR DESCRIPTION
**Pull request by SaraBoutej**
In this PR we add role presentation for all user and space avatar, because we consider them as decorative images.

### CODE REVIEW

**Comment by rdenarie** [comment]
@SaraBoutej Sonar make an alert for missing alt on the image you change.
Can you check if the alert is relevant or not

**Comment by SaraBoutej** [comment]
> @SaraBoutej Sonar make an alert for missing alt on the image you change. Can you check if the alert is relevant or not

@rdenarie I made changes on avatar image that must be considered as a decorative image (with **no alt attribute** and by adding ro**le presentation**) to be ignored by Assistive Technology.

**Comment by rdenarie** [comment]
So I remove the sonar alert

**Review by rdenarie — DISMISSED** [review]

**Comment by SaraBoutej** [comment]
> So I remove the sonar alert

@rdenarie can you please Reapprove

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
