### PR TITLE
fix: Unpublish news problem after editing news title - EXO-61538

### PR DESCRIPTION
**Pull request by Jihed525**
* fix: before this change, after changing the title of the published news, the Un-publishing of the news can't be done and the publish button keeps loading, since it can't find the shared news with its new title, it throws an exception that is not handled. After this change, once news title is edited, the published news is removed and the updated news is published and un-published news problem after editing news title - EXO-61538

(cherry picked from commit f8c35f2fcc58bf37cb93ae0717d680acfb0fb763)

### CODE REVIEW

**Comment by exo-swf** [comment]
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

**Comment by exo-swf** [comment]
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

**Comment by exo-swf** [comment]
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

**Review by GouadriaHanen — DISMISSED** [review]

**Comment by exo-swf** [comment]
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

**Comment by exo-swf** [comment]
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

**Review by GouadriaHanen — APPROVED** [review]

**Pull request merged**
